name: deploy-doc-to-github-pages
on:
  push:
    branches:
      - 'master'
jobs:
  deploy-swagger-doc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install node 10.15
        uses: actions/setup-node@v2
        with:
          node-version: '10.15'
      - name: clean and install dependencies
        run: | 
          echo "ğŸ§ Getting the project dependencies"
          npm ci
      - name: build documentation web
        run: | 
          echo "ğŸ§ Building and deploying the web to github pages"
          npm run build
      - name: deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: web_deploy